<a href="https://colab.research.google.com/github/EstelleYang111/MSSP607/blob/main/WeeklyModules/Week05/Participation_Activity_Week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

aapl = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week05/aapl.csv')
amzn = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week05/amzn.csv')
nflx = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week05/nflx.csv')
fb = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week05/fb.csv')
goog = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week05/goog.csv')

In [ ]:
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
nflx['ticker'] = 'NFLX'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'

In [ ]:
aapl.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [ ]:
faang = pd.concat([fb, aapl, amzn, nflx, goog], ignore_index=True)

faang.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

In [ ]:
faang.to_csv('/content/drive/MyDrive/MSSP607/Modules/Week05/faanf.csv', index=False)

In [ ]:
faang = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week05/faanf.csv')

faang.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

In [ ]:
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype(int)

faang.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

In [ ]:
faang = faang.sort_values(by=['date', 'ticker'])

faang.head()

           date       open       high        low      close    volume ticker
251  2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
502  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0    2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
753  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [ ]:
faang.nlargest(7, 'volume')

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [ ]:
melted = faang.melt(
    id_vars=['date', 'ticker']
)

melted.head(10)

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000
5 2018-01-03   AAPL     open   169.2521
6 2018-01-03   AMZN     open  1188.3000
7 2018-01-03     FB     open   181.8800
8 2018-01-03   GOOG     open  1064.3100
9 2018-01-03   NFLX     open   202.0500